In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
cd drive/MyDrive/code/project_job_20/

/content/drive/MyDrive/code/project_job_20


In [18]:
pwd

'/content/drive/MyDrive/code/project_job_20'

In [19]:
with open('payload.txt') as f:
    alist = [line.rstrip() for line in f.readlines()]

In [20]:
import numpy as np

In [21]:
alist_array=np.array(alist)

In [22]:
import requests

In [32]:
data=np.array([])
for i in alist_array:
    url="https://stripe.com/en-in"+i
    o=requests.get(url)
    power=np.append(data,[o.status_code,url])

In [27]:
data

array([], dtype=float64)

In [33]:
power

array(['400',
       'https://stripe.com/en-in////www.whitelisteddomain.tld@google.com/%2f..'],
      dtype='<U70')

# above coding area ^

In [ ]:
st="https://stripe.com/en-in"

In [ ]:
st+alist[1]

'https://stripe.com/en-in/%2f%2fexample.com'

In [2]:
tow=np.array([3,4,4,5])

In [8]:
%timeit
for i in tow:
    print(i)
%time

3
4
4
5
CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 5.25 µs


In [9]:
for i in [3,4,4,5]:
    print(i)
%time

3
4
4
5
CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 9.78 µs


In [28]:
np.append(tow,[42,43])

array([ 3,  4,  4,  5, 42, 43])

In [29]:
np.append(tow,[42,43])

array([ 3,  4,  4,  5, 42, 43])

In [30]:
row=np.append(tow,[42,43])

In [31]:
row

array([ 3,  4,  4,  5, 42, 43])