In [ ]:
list(map(lambda a:a**2,[3,3,2,3,35,34,3,4]))

[9, 9, 4, 9, 1225, 1156, 9, 16]

In [ ]:
list(filter(lambda a : a%2==0,[3,3,2,3,35,34,3,4]))

[2, 34, 4]

In [2]:
import os
import matplotlib.pyplot as plt

In [3]:
import tensorflow as tf

In [4]:
tf.__version__

'2.5.0'

In [5]:
tf.executing_eagerly()

True

In [6]:
train_dataset_url='https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv'

In [7]:
train_dataset_fp=tf.keras.utils.get_file(fname=os.path.basename(train_dataset_url),origin=train_dataset_url)

8192/2194 [================================================================================================================] - 0s 0us/step


# this is minist data predict useing tensorflow

In [8]:
model_data=tf.keras.datasets.mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [9]:
(xtrain,ytrain),(xtest,ytest)=model_data

In [10]:
x_train,x_test=xtrain/255.0,xtest/255.0

In [43]:
model=tf.keras.Sequential([
                           tf.keras.layers.Flatten(input_shape=(28,28)),
                           tf.keras.layers.Dense(128,activation='relu'),
                           tf.keras.layers.Dropout(0.2),
                           tf.keras.layers.Dense(10)
])

In [44]:
prediction=model(x_train[:1]).numpy()

In [47]:
prediction

array([[ 0.27166888, -0.05016728,  0.20196772, -0.05592822,  0.12198789,
        -0.5004512 , -0.66663027,  0.81094694,  0.12381689, -0.60243404]],
      dtype=float32)

In [55]:
tf.nn.softmax(prediction).numpy()*100

array([[12.365503 ,  8.962727 , 11.532966 ,  8.911241 , 10.646483 ,
         5.7132645,  4.8385324, 21.203976 , 10.665974 ,  5.1593347]],
      dtype=float32)

In [56]:
loss_fuc=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [58]:
loss_fuc(ytrain[:1],prediction)

<tf.Tensor: shape=(), dtype=float32, numpy=2.8623796>

In [60]:
model.compile(optimizer='adam',
loss=loss_fuc,
metrics=['accuracy'])

In [62]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6044 - accuracy: 0.8360
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5053 - accuracy: 0.8611
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4336 - accuracy: 0.8835
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4080 - accuracy: 0.8899
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3794 - accuracy: 0.8990


In [67]:
model.evaluate(xtest,ytest,verbose=2)

313/313 - 0s - loss: 0.2793 - accuracy: 0.9311


[0.279341459274292, 0.9311000108718872]

In [39]:
ytrain[:1]

array([5], dtype=uint8)

In [ ]:
x_train.shape

(60000, 28, 28)

In [25]:
import pandas as pd

In [34]:
pd.DataFrame(xtrain.reshape(60000,28*28))

0    1    2    3    4    5    6    ...  777  778  779  780  781  782  783
0        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4        0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
59995    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59996    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59997    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59998    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
59999    0    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[60000 rows x 784 columns]

In [33]:
xtrain.reshape(60000,28*28)

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)