# Chapter 1 
* all Regression Allgorithm use 
* Quick look theory part  (what, why & how) 
, use this [link](https://scikit-learn.org/stable/modules/linear_model.html#polynomial-regression-extending-linear-models-with-basis-functions)

* all Regression Allgorithm use again mind but you know how it work & why.
* all Important point cover What, why & how . (pros & coes)
## Deep Dive into the Regression  it make you Advance level player in the game.
* make Algorithms from skreatch.
* & do a few projects for real world exprences. 

Notics :- You must perelley learn the some statistics & Probabilty use below link

statistics:-    https://youtube.com/playlist?list=PL1328115D3D8A2566

probability:-   https://www.youtube.com/playlist?list=PLC58778F28211FA19

After Finishing above topic you changing you level expert to max expert in Regression 

# All Regression Allgorithm use for how to use it.
(because it make question on your brain to help in study. this is also work)

**so, what is Regression? rise in you mind.**

Regression analysis is a form of predictive modelling technique which investigates the relationship between a dependent (target) and independent variable (s) (predictor). 

This technique is used for forecasting, time series modelling and finding the causal effect relationship between the variables.

## Types of Regression 
* Linear Regression
* Logistic Regression
* Polynomial Regression
* Stepwise Regression
* Ridge Regression
* Lasso Regression
* ElasticNet Regression


# Linear Regression     

In [4]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
model = LinearRegression(n_jobs=3,copy_X=False)

In [5]:
X=np.array([[1,1],[1,2],[2,2],[2,3]])
y=np.dot(X,np.array([1,2])) +3        # 1*x_0 + 2*x_1 +3 

In [6]:
model.fit(X,y)

LinearRegression(copy_X=False, fit_intercept=True, n_jobs=3, normalize=False)

In [7]:
model.coef_

array([1., 2.])

In [8]:
model.intercept_

3.0000000000000018

In [9]:
X_test=np.array([[3,3],[3,4],[4,4],[4,5]])
y_test=np.dot(X_test,np.array([1,2])) + 3

In [10]:
y_test

array([12, 14, 15, 17])

In [11]:
model.score(X,y)

1.0

In [12]:
y_estimat =model.predict(X_test)

correlation of X & Y 

In [13]:
model.score(X_test,y_test)         # score say X , Y relationship is good if 1 or negative values is bed relationship.

1.0

In [14]:
y_estimat

array([12., 14., 15., 17.])

In [15]:
model.get_params()

{'copy_X': False, 'fit_intercept': True, 'n_jobs': 3, 'normalize': False}

In [16]:
above=((y_test - y_estimat) ** 2).sum() 

In [17]:
blow=((y_test - y_test.mean()) ** 2).sum()

In [18]:
1-(above/blow)

1.0

In [19]:
above/blow

4.854528647513919e-31

# Polynomial Regression

In [20]:
model.intercept_+(model.coef_*X**2)

array([[ 4.,  5.],
       [ 4., 11.],
       [ 7., 11.],
       [ 7., 21.]])

In [21]:
from sklearn.preprocessing import PolynomialFeatures

In [22]:
poly=PolynomialFeatures(degree=1)

In [23]:
poly.fit(X)

PolynomialFeatures(degree=1, include_bias=True, interaction_only=False,
                   order='C')

In [24]:
poly.fit_transform(X)

array([[1., 1., 1.],
       [1., 1., 2.],
       [1., 2., 2.],
       [1., 2., 3.]])

In [25]:
X

array([[1, 1],
       [1, 2],
       [2, 2],
       [2, 3]])

In [28]:
from sklearn.datasets import make_regression

In [55]:
X,y=make_regression(n_samples=1,n_targets=100)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt


# Logistic Regression

In [ ]:
from sklearn.datasets import load_iris

In [ ]:
X,y=load_iris(return_X_y=True)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model1=LogisticRegression()

In [ ]:
X.size

600

In [ ]:
model1.fit(X[0:100,np.newaxis],y[0:100])

ValueError: ignored

In [ ]:
X.shape

# Stepwise Regression

In [ ]:
import numpy as np
import statsmodels.api as sm
def get_stats():
    x = X
    results = sm.OLS(y, x).fit()
    print(results.summary())
    
get_stats()

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.972
Model:                            OLS   Adj. R-squared (uncentered):              0.971
Method:                 Least Squares   F-statistic:                              1267.
Date:                Tue, 18 May 2021   Prob (F-statistic):                   3.17e-112
Time:                        15:07:19   Log-Likelihood:                          17.009
No. Observations:                 150   AIC:                                     -26.02
Df Residuals:                     146   BIC:                                     -13.98
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

# Ridge Regression

In [ ]:
from sklearn.linear_model import Ridge
model3=Ridge()

In [ ]:
n_samples, n_features = 10, 5

rng = np.random.RandomState(0)

y = rng.randn(n_samples)


X = rng.randn(n_samples, n_features)

clf = Ridge(alpha=1.0)


clf.fit(X, y)




Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [ ]:
clf.predict(X)

array([ 0.95424223,  0.48712089,  1.10388121,  1.79105759,  1.05769745,
       -0.07915715,  1.12314109, -0.22941441,  0.64906337,  0.52259943])

In [ ]:
y

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

# ElasticNet Regression

In [ ]:
print('helo')

helo


In [ ]:
from sklearn.linear_model import ElasticNet
from sklearn.datasets import make_regression

In [ ]:
X,y=make_regression(n_features=2,random_state=42)

In [ ]:
X.shape

(100, 2)

In [ ]:
y.shape

(100,)

In [ ]:
regr=ElasticNet(random_state=41)

In [ ]:
regr.fit(X,y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=41, selection='cyclic', tol=0.0001, warm_start=False)

# Now next level